# Generated by Django 4.2.2 on 2025-01-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Appointment Scheduled', 'Appointment Scheduled'), ('Appointmen Cancelled', 'Appointmen Cancelled')], max_length=100),
        ),
    ]
