# Generated by Django 4.2.2 on 2025-01-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Appointmen Cancelled', 'Appointmen Cancelled'), ('Appointment Scheduled', 'Appointment Scheduled')], max_length=100),
        ),
    ]
