# Generated by Django 4.2.2 on 2025-01-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
