# Generated by Django 4.2.2 on 2025-01-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Appointmen Cancelled', 'Appointmen Cancelled'), ('New Appointment', 'New Appointment')], max_length=100),
        ),
    ]
