# Generated by Django 4.2.2 on 2025-01-23 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_available_appointment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
