# Generated by Django 4.2.2 on 2025-01-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctor_next_available_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Appointmen Cancelled', 'Appointmen Cancelled'), ('New Appointment', 'New Appointment')], max_length=100),
        ),
    ]
